name       : trelby
version    : 2.2
release    : 1
source     :
    - http://www.trelby.org/files/release/2.2/trelby-2.2.tar.gz : a46661507444a7ba80a3202fd637220198853db7b6b6cb3a0ce441c7eb6f72e6
license    : GPL-2.0
summary    : Trelby is a screenplay writing program.
description: |
    Trelby is a screenplay writing program.
homepage   : http://www.trelby.org
rundeps    :
    - python-lxml
    - python-setuptools
    - wxPython2
install    : |
    install -Dm644 trelby/trelby.desktop $installdir/usr/share/applications/trelby.desktop
    install -Dm644 trelby/resources/icon256.png $installdir/usr/share/trelby/resources/icon256.png
    mkdir -p $installdir/opt/
    cp -r trelby $installdir/opt/
    sed -i '4i import wxversion' $installdir/opt/trelby/src/trelby.py
    sed -i '5i wxversion.select("2.8")' $installdir/opt/trelby/src/trelby.py
