name       : trelby
version    : 2.4.8
release    : 7
source     :
    - https://github.com/limburgher/trelby/archive/refs/tags/2.4.8.tar.gz : 3ed1143aa24eb2b6385495c8d13f8bd9875ce36d539df8baecf3eb9edbcf89c5
license    : GPL-2.0-or-later
homepage   : http://www.trelby.org/
component  : office
summary    : Trelby is a screenplay writing program.
description: |
    The free, multiplatform, feature-rich screenwriting program!
builddeps  :
    - wxPython
    - wxwidgets-devel
rundeps    :
    - python-lxml
    - wxPython
setup      : |
    sed -i 's:/opt/trelby:/usr/share/trelby:g' setup.cfg
build      : |
    %python3_setup
install    : |
    %python3_install
    install -dm00644 $installdir/usr/bin
    ln -s /usr/share/trelby/bin/trelby $installdir/usr/bin/trelby
    install -Dm00644 trelby.desktop $installdir/usr/share/applications/trelby.desktop
    install -Dm00644 resources/icon256.png $installdir/usr/share/trelby/resources/icon256.png
