name       : trelby
version    : '2.2'
release    : 6
source     :
    - git|https://github.com/oskusalerma/trelby.git : 580222d3ea181586c18442600ed26c01f67e2654
license    : GPL-2.0-or-later
component  : office
summary    : Trelby is a screenplay writing program.
description: |
    Trelby is a screenplay writing program.
builddeps  :
    - python-setuptools
    - wxPython
    - wxPython2
    - wxwidgets-devel
rundeps    :
    - python-lxml
    - wxPython
    - wxwidgets
setup      : |
    sed -i 's:/opt/trelby:/usr/share/trelby:g' setup.cfg
build      : |
    %python_setup
install    : |
    %python_install
    install -dm00644 $installdir/usr/bin
    ln -s /usr/share/trelby/bin/trelby $installdir/usr/bin/trelby
    install -Dm00644 trelby.desktop $installdir/usr/share/applications/trelby.desktop
    install -Dm00644 resources/icon256.png $installdir/usr/share/trelby/resources/icon256.png
